### ISSUE TITLE
Html file returned in resource-response not handled correctly when auto-refresh is enabled

### ISSUE THREAD

**Issue by sid-kurias** [weavejester/ring-refresh#1]
In project.clj setup ring to auto refresh.

:ring {:handler myapp.core/app
     :auto-reload? true
     :auto-refresh? true
         :adapter {:aliases "true"}
    }

Then in your application route definitions, return a resource that points to an html file.
//using compojure 1.1.3, ring 1.1.6

(defroutes main-routes
  (route/resources "/" {:root "public"})
  (GET "/*" []  (resource-response "index.html" {:root "public"}))
  (route/not-found "Page not found"))

This will cause a null pointer exception to be thrown

Matcher.java:1234   java.util.regex.Matcher.getTextLength
Matcher.java:308    java.util.regex.Matcher.reset
Matcher.java:228    java.util.regex.Matcher.<init>
Pattern.java:1088   java.util.regex.Pattern.matcher
core.clj:4286   clojure.core/re-matcher
core.clj:4338   clojure.core/re-find
refresh.clj:18  ring.middleware.refresh/html-content?
refresh.clj:84  ring.middleware.refresh/wrap-with-script[fn]
core.clj:106    compojure.core/routing[fn]
core.clj:2390   clojure.core/some
core.clj:106    compojure.core/routing
RestFn.java:139 clojure.lang.RestFn.applyTo
core.clj:603    clojure.core/apply
core.clj:111    compojure.core/routes[fn]
params.clj:55   ring.middleware.params/wrap-params[fn]
stacktrace.clj:15   ring.middleware.stacktrace/wrap-stacktrace-log[fn]
stacktrace.clj:79   ring.middleware.stacktrace/wrap-stacktrace-web[fn]
reload.clj:18   ring.middleware.reload/wrap-reload[fn]
jetty.clj:18    ring.adapter.jetty/proxy-handler[fn](Unknown Source)    ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$0.handle
HandlerWrapper.java:111 org.eclipse.jetty.server.handler.HandlerWrapper.handle
Server.java:349 org.eclipse.jetty.server.Server.handle
AbstractHttpConnection.java:452 org.eclipse.jetty.server.AbstractHttpConnection.handleRequest
AbstractHttpConnection.java:884 org.eclipse.jetty.server.AbstractHttpConnection.headerComplete
AbstractHttpConnection.java:938 org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete
HttpParser.java:634 org.eclipse.jetty.http.HttpParser.parseNext
HttpParser.java:230 org.eclipse.jetty.http.HttpParser.parseAvailable
AsyncHttpConnection.java:76 org.eclipse.jetty.server.AsyncHttpConnection.handle
SelectChannelEndPoint.java:609  org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle
SelectChannelEndPoint.java:45   org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run
QueuedThreadPool.java:599   org.eclipse.jetty.util.thread.QueuedThreadPool.runJob
QueuedThreadPool.java:534   org.eclipse.jetty.util.thread.QueuedThreadPool$3.run
Thread.java:722 java.lang.Thread.run

**Comment by RyanMcG** [comment]
I am encountering a similar issue. Was this ever resolved?

**Comment by sid-kurias** [comment]
yes it was. A long time ago or at least long enough that I can't remember the issue anymore :-), except I remember it was fixed. So  there must have been a regression lately, assuming you are using the latest versions.

On Tuesday, May 27, 2014 9:23 AM, Ryan McGowan notifications@github.com wrote:

I am encountering a similar issue. Was this ever resolved?

**Comment by RyanMcG** [comment]
@sid-kurias Not to worry. I reordered some middlewares and everything is working now.
