### ISSUE TITLE
Warning about clojure.core.incubator/seqable? shadowing clojure.core output when using Clojure 1.10.3

### ISSUE THREAD

**Issue by stevejmp** [weavejester/ring-refresh#11]
## Expected
Running in a project using ring-refresh and Clojure version `1.10.3`, should output no warnings or exceptions when run.

## Actual
```
WARNING: seqable? already refers to: #'clojure.core/seqable? in namespace: clojure.core.incubator, being replaced by: #'clojure.core.incubator/seqable?
```

## Steps to Reproduce
1. In a project using ring-refresh, set the Clojure dep to `1.10.3`
2. Run a task using ring-refresh from a terminal
3. View the output

## Versions
Ring-Refresh 0.1.2 (lein-ring 0.12.6 -> lein-server 0.5.0 -> ring-refresh 0.1.2)
Clojure 1.10.3
Java 11.0.14
Leiningen 2.9.8

## More Info

A `seqable?` function was added to `clojure.core` in `1.9.0`.

In the REPL, the warning goes away when commenting out the only [`compojure.core` dependency](https://github.com/weavejester/ring-refresh/blob/9115d8510808b9c83f9fa3296043527b4c78094e/src/ring/middleware/refresh.clj#L2) and related code in `refresh`. The warning returns when uncommenting the single dependency. 

Currently, the project specifies the Compojure dependency as `1.1.5`. If the version is bumped to the latest, `1.6.2`, the warning goes away.

I'm not familiar enough with all the Ring-Refresh use cases to know if bumping the Compojure dependency will cause any breakage.

Any feedback?

I may dig deeper later and submit a PR.

**Comment by weavejester** [comment]
It's fine to update the dependency.
