### ISSUE TITLE
Don't check for status code?

### ISSUE THREAD

**Issue by Frozenlock** [weavejester/ring-refresh#15]
Any exception will cause the refresh middleware to be deactivated until the user fixes the error and manually refreshes the page.
This is suboptimal when used with `ring.middleware.stacktrace`, as the html returned works well with the injected html.

Given that the middleware already checks for `get-request?` and `html-content?`, perhaps there's no need to also check for status code?

I'm currently using this hacked solution and it works well:

```clj
(defn wrap-refresh
  [handler]
  (let [wrap-success (fn [h]
                       (fn [req]
                         (with-redefs [ring.middleware.refresh/success? (constantly true)]
                           (h req))))]
    (-> handler
        (refresh/wrap-refresh)
        (wrap-success))))
```

**Comment by weavejester** [comment]
That's a reasonable change, I think. I'd welcome a PR.

**Comment by Frozenlock** [comment]
Is the PR adequate?
