### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by johnbendi** [weavejester/ring-refresh#2]
I don't know why I'm getting this exception:

java.lang.NullPointerException
Var.java:415    clojure.lang.Var.invoke
refresh.clj:80  ring.middleware.refresh/wrap-with-script[fn]
core.clj:98 compojure.core/routing[fn]
core.clj:2390   clojure.core/some
core.clj:98 compojure.core/routing
RestFn.java:139 clojure.lang.RestFn.applyTo
core.clj:603    clojure.core/apply
core.clj:103    compojure.core/routes[fn]
params.clj:55   ring.middleware.params/wrap-params[fn]
reload.clj:18   ring.middleware.reload/wrap-reload[fn]
stacktrace.clj:15   ring.middleware.stacktrace/wrap-stacktrace-log[fn]
stacktrace.clj:79   ring.middleware.stacktrace/wrap-stacktrace-web[fn]
jetty.clj:18    ring.adapter.jetty/proxy-handler[fn](Unknown Source)    ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$0.handle
HandlerWrapper.java:111 org.eclipse.jetty.server.handler.HandlerWrapper.handle
Server.java:349 org.eclipse.jetty.server.Server.handle
AbstractHttpConnection.java:452 org.eclipse.jetty.server.AbstractHttpConnection.handleRequest
AbstractHttpConnection.java:884 org.eclipse.jetty.server.AbstractHttpConnection.headerComplete
AbstractHttpConnection.java:938 org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete
HttpParser.java:634 org.eclipse.jetty.http.HttpParser.parseNext
HttpParser.java:230 org.eclipse.jetty.http.HttpParser.parseAvailable
AsyncHttpConnection.java:76 org.eclipse.jetty.server.AsyncHttpConnection.handle
SelectChannelEndPoint.java:609  org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle
SelectChannelEndPoint.java:45   org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run
QueuedThreadPool.java:599   org.eclipse.jetty.util.thread.QueuedThreadPool.runJob
QueuedThreadPool.java:534   org.eclipse.jetty.util.thread.QueuedThreadPool$3.run
Thread.java:679 java.lang.Thread.run

**Comment by weavejester** [comment]
Could you tell me which version of ring-refresh you're using, and what the route looks like that it's failing on.

**Comment by johnbendi** [comment]
I am not depending on ring-refresh directly. I am using the dependency of ring-server 0.2.8

**Comment by weavejester** [comment]
The error message seems to indicate you're passing a nil value to the middleware instead of a Ring handler. I'm afraid I'd need to see some code before being able to say anything more.

**Comment by tvaughan** [comment]
I was just bit by this. Granted, I'm using much newer versions of these libraries but still the stacktrace was very similar. The problem, for me at least, was that in project.clj I had something like `:ring {:handler my-app.handlers/a-function-that-does-not-exist}`. Oops.
