### ISSUE TITLE
0.1.2 on Clojars but the commit doesn't exist

### ISSUE THREAD

**Issue by fzakaria** [weavejester/ring-refresh#3]
The current version of ring-refresh on Clojars is 0.1.2 
https://clojars.org/ring-refresh

It lists a commit that doesn't exist:
https://github.com/weavejester/ring-refresh/commit/a10c5f38dadde7b3a03078f77957a90844ed7f58

The master branch however is on 0.1.1

Is there a mistake ?

**Comment by weavejester** [comment]
Forgot to push. Fixed now.

**Comment by fzakaria** [comment]
sweet thanks
