### ISSUE TITLE
Compilation hanging

### ISSUE THREAD

**Issue by roberttaylor426** [weavejester/ring-refresh#5]
Hi,

I've recently added `ring-refresh` to my project and am experiencing intermittent hangs during compilation.

The first attempt to run the project will hang at `Compiling xyz`. If I kill the process and then try to run a second time it will successfully start the server.

I'm not really sure how to debug this. I've tried running with `DEBUG=y`, which shows:

```
Leiningen's classpath: ~/.lein/self-installs/leiningen-2.9.3-standalone.jar
Applying task [run 8090] to []
Applying task javac to nil
Running javac with [@/tmp/.leiningen-cmdline8289298169645049757.tmp]
Applying task compile to nil
Compiling xyz
```
The only difference in the output on the second run is that instead of showing `Compiling xyz` it says:
```
All namespaces already AOT compiled.
```
before starting up successfully.

My versions of lein and java are as follows:

```
lein -version
Leiningen 2.9.3 on Java 1.8.0_252 OpenJDK 64-Bit Server VM
```

Any pointers would be greatly appreciated!

**Comment by weavejester** [comment]
You'll need to provide a little more information. By "compiling", do you mean AoT compilation? Are you compiling one namespace or many? Why are you using ring-refresh with AoT compilation?

**Comment by roberttaylor426** [comment]
Thanks for the quick response @weavejester. Apologies for the lack of clarity - I'm fairly new to Clojure and Leiningen. 

Yes, by compiling I do mean AoT compilation. If I disable AoT I can start my web server locally without issue. I _do_ need AoT it seems for building an uberjar from my project, but I guess I will need to find a way to exclude any dependency on `ring-refresh` when doing that (given that your docs state 'This library is designed for use only in development environments.').

Thanks for your help!
